parser: "babel-eslint" # for class properties
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: "module"

extends: "google"
plugins:
  - "react"
rules:
  object-curly-spacing:
  # airbnb rule
    - 2
    - "always"
  camelcase: 0
  max-len:
    - 2
    - ignoreTemplateLiterals: true
    - ignoreUrls: true
  new-cap: 
    - 2
    - capIsNewExceptions: # immutable.js types
      - "List"
      - "Map"
      - "Set"
  react/jsx-uses-vars: 1